name = "Vno"
license = "CC BY-NC-SA 4.0"
licenselink = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
description = "A Simple and Responsive blog theme for Hugo."
homepage = "https://github.com/RedContritio/vno-hugo"
# demosite = "https://vno-hugo.netlify.app/"
tags = ["blog", "responsive","dark", "light"]
features = ["blog", "responsive", "darkmode", "pagination", "social-menu"]
min_version = "0.54.0"

# If the theme has a single author
[author]
    name = "RedContritio"
    homepage = "https://github.com/RedContritio"

# If porting an existing theme
[original]
    author = "xsling"
    homepage = "https://github.com/xslingcn"
    repo = "https://github.com/xslingcn/vno-hugo"
